import { pgTable, bigint, varchar, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  id_pengguna: bigint('id_pengguna', { mode: 'number' }),
  id_peran: bigint('id_peran', { mode: 'number' }),
  id_instansi: varchar('id_instansi'),
  id_induk: bigint('id_induk', { mode: 'number' }),
  id_koordinator: bigint('id_koordinator', { mode: 'number' }),
  id_wilayah: varchar('id_wilayah'),
  id_upp: bigint('id_upp', { mode: 'number' }),
  name: varchar('name'),
  email: varchar('email'),
  username: varchar('username'),
  email_verified_at: timestamp('email_verified_at', { withTimezone: true }),
  password: varchar('password'),
  telp: varchar('telp'),
  nm_peran: varchar('nm_peran'),
  nm_instansi: varchar('nm_instansi'),
  nm_upp: varchar('nm_upp'),
  nm_wilayah: varchar('nm_wilayah'),
  remember_token: varchar('remember_token'),
  last_login: timestamp('last_login', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }),
  updated_at: timestamp('updated_at', { withTimezone: true }),
  recaptcha_response: text('recaptcha_response'),
  is_active: text('is_active'),
  is_changepass: text('is_changepass'),
  is_del: text('is_del'),
  google_id: text('google_id'),
  log_abnormal: varchar('log_abnormal'),
  is_pkri: text('is_pkri'),
});
